set(_CATKIN_CURRENT_PACKAGE "optitrack")
set(optitrack_VERSION "0.0.0")
set(optitrack_MAINTAINER "ce912 <ce912@todo.todo>")
set(optitrack_PACKAGE_FORMAT "2")
set(optitrack_BUILD_DEPENDS "rospy" "geometry_msgs" "nav_msgs" "std_msgs")
set(optitrack_BUILD_EXPORT_DEPENDS )
set(optitrack_BUILDTOOL_DEPENDS "catkin")
set(optitrack_BUILDTOOL_EXPORT_DEPENDS )
set(optitrack_EXEC_DEPENDS "rospy" "geometry_msgs" "nav_msgs" "std_msgs")
set(optitrack_RUN_DEPENDS "rospy" "geometry_msgs" "nav_msgs" "std_msgs")
set(optitrack_TEST_DEPENDS )
set(optitrack_DOC_DEPENDS )
set(optitrack_URL_WEBSITE "")
set(optitrack_URL_BUGTRACKER "")
set(optitrack_URL_REPOSITORY "")
set(optitrack_DEPRECATED "")